In [1]:
import torch
from torch import nn

from rnn import StochasticLSTM

In [2]:
torch.random.manual_seed(1)

In [9]:
t = torch.randn((1, 1, 2))
print(t)
l = StochasticLSTM(input_size=2, hidden_size=4, dropout_rate=0.5)
print(l(t))

tensor([[[0.6614, 0.2669]]])
(tensor([[[0.5279, 0.4958, 0.5911, 0.5030]]], grad_fn=<MeanBackward1>), (tensor([[[-0.0495, -0.0552, -0.1094,  0.0431]]], grad_fn=<MeanBackward1>), tensor([[[-0.0900, -0.1132, -0.1730,  0.0897]]], grad_fn=<MeanBackward1>)))


In [3]:
t = torch.randn((1, 1, 2))
print(t)
l = StochasticLSTM(input_size=2, hidden_size=4, dropout_rate=0.5)
print(l(t))

tensor([[[0.6614, 0.2669]]])
(tensor([[[0.5330, 0.6375, 0.3270, 0.5796]]], grad_fn=<MeanBackward1>), (tensor([[[ 0.2213,  0.1360, -0.0428,  0.1776]]], grad_fn=<MeanBackward1>), tensor([[[ 0.4443,  0.2159, -0.1270,  0.3154]]], grad_fn=<MeanBackward1>)))


In [5]:
l = StochasticLSTM(input_size=3, hidden_size=4, dropout_rate=0.5)

In [3]:
t = torch.randn((5, 10, 3))

In [4]:
output, (h, c) = l(t)

In [12]:
l = nn.Linear(2, 3)

In [15]:
l

TypeError: type() missing 1 required positional argument: 'dst_type'

In [4]:
a = torch.zeros(3, 3)
b = torch.zeros(3, 3, requires_grad=True)

In [9]:
a

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [58]:
a = torch.randn(3, 4)
a

tensor([[-0.1570,  0.6643,  1.7571,  0.0559],
        [ 1.1614,  0.3632,  1.7422, -0.3796],
        [ 1.4920, -0.0075,  1.1378,  1.6018]])

In [60]:
torch.stack([a, a])

tensor([[[-0.1570,  0.6643,  1.7571,  0.0559],
         [ 1.1614,  0.3632,  1.7422, -0.3796],
         [ 1.4920, -0.0075,  1.1378,  1.6018]],

        [[-0.1570,  0.6643,  1.7571,  0.0559],
         [ 1.1614,  0.3632,  1.7422, -0.3796],
         [ 1.4920, -0.0075,  1.1378,  1.6018]]])

In [50]:
[].append(a)

In [51]:
c = []
c.append(a)

In [52]:
c

[tensor([[ 0.3990, -0.1427, -1.4446, -1.1207],
         [-1.7007,  0.8732,  1.2721, -0.5493],
         [ 1.1034,  0.0232,  0.0135, -0.1820]])]